# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Deploy

on:
  push:
    branches: [ "flask" ]
  pull_request:
    branches: [ "flask" ]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: LS command
      run: ls
    - name: PWD command
      run: pwd
    - name: cp command
      run: cp -r * /home/alex/VDI-APP-INSA
    - name: api-service restart
      run: sudo systemctl restart app-vdi
    - name: api-service status
      run: sudo systemctl status app-vdi
